test failure step

diff --git a/.github/workflows/thirteenth_workflow.yml b/.github/workflows/thirteenth_workflow.yml
--- a/.github/workflows/thirteenth_workflow.yml
+++ b/.github/workflows/thirteenth_workflow.yml
@@ -6,6 +6,9 @@ jobs:
     job:
       runs-on: ubuntu-latest
       steps: 
+        - name: Failure Step
+          id: error-step
+          run: exit 1
         - name: First Step
           run: sleep 30
         - name: Runs on Cancelled
@@ -18,7 +21,7 @@ jobs:
           if: ${{ success() }}
           run: echo "Runs on Success"
         - name: Runs on Failure
-          if: ${{ failure() }}
+          if: ${{ failure() && steps.error-step.conclusion == 'failure' }}
           run: echo "Runs on Failure"
     second-job:
       runs-on: ubuntu-latest
