test failed

diff --git a/.github/workflows/thirteenth_workflow.yml b/.github/workflows/thirteenth_workflow.yml
--- a/.github/workflows/thirteenth_workflow.yml
+++ b/.github/workflows/thirteenth_workflow.yml
@@ -7,7 +7,7 @@ jobs:
       runs-on: ubuntu-latest
       steps: 
         - name: First Step
-          run: sleep 30
+          run: exit 1
         - name: Runs on Cancelled
           if: ${{ cancelled() }}
           run: echo "Runs on Cancelled"
@@ -20,3 +20,9 @@ jobs:
         - name: Runs on Failure
           if: ${{ failure() }}
           run: echo "Runs on Failure"
+    second-job:
+      runs-on: ubuntu-latest
+      needs: job
+      if: ${{ failure() }}
+      steps:
+        - run: echo "job was failed"
